# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: parser.proto for package 'twittertext'

require 'grpc'
require 'parser'

module Twittertext
  module TwitterText

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'twittertext.TwitterText'

      rpc :Parse, TweetRequest, ParsedResponse
    end

    Stub = Service.rpc_stub_class
  end
end
